Name:           perl-FusionInventory-Agent-Task-Deploy
Version:        2.0.0
Release:        1%{?dist}
Summary:        Software deployment support for FusionInventory Agent
License:        GPLv2+
Group:          Development/Libraries
URL:            http://search.cpan.org/dist/FusionInventory-Agent-Task-Deploy/
Source0:        http://search.cpan.org/CPAN/authors/id/F/FU/FUSINV/FusionInventory-Agent-Task-Deploy-%{version}.tar.gz

BuildRoot:      %{_tmppath}/%{name}-%{version}-%{release}-root-%(%{__id_u} -n)
BuildArch:      noarch
BuildRequires:  perl >= 1:5.8.0
BuildRequires:  perl(Archive::Extract)
BuildRequires:  perl(Archive::Tar)
BuildRequires:  perl(Digest::SHA)
BuildRequires:  perl(ExtUtils::MakeMaker)
BuildRequires:  perl(File::Copy::Recursive)
BuildRequires:  perl(JSON)
BuildRequires:  perl(POE::Component::Client::Ping)
BuildRequires:  perl(Test::Compile)
BuildRequires:  perl(Test::HTTP::Server::Simple)
BuildRequires:  perl(URI::Escape)
BuildRequires:  perl(FusionInventory::Agent) >= 2.2.0
%if 0%{?fedora} >= 14
BuildRequires:  perl(HTTP::Server::Simple::Authen) perl(CGI)
%endif

Requires:       perl(FusionInventory::Agent) >= 2.2.0
Requires:       perl(Archive::Extract)
Requires:       perl(Digest::SHA)
Requires:       perl(File::Copy::Recursive)
Requires:       perl(JSON)
Requires:       perl(POE::Component::Client::Ping)
Requires:       perl(URI::Escape)
Requires:       perl(:MODULE_COMPAT_%(eval "`%{__perl} -V:version`"; echo $version))

%description
With this module, FusionInventory can accept software deployment request
from an GLPI server with the FusionInventory plugin.


%prep
%setup -q -n FusionInventory-Agent-Task-Deploy-%{version}


%build
perl Makefile.PL \
     PREFIX=%{_prefix} \
     SYSCONFDIR=%{_sysconfdir}/fusioninventory \
     LOCALSTATEDIR=%{_localstatedir}/lib/%{name}

make %{?_smp_mflags}


%install
rm -rf %{buildroot}

make pure_install DESTDIR=%{buildroot}

find %{buildroot} -type f -name .packlist -exec rm -f {} \;
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null \;

%{_fixperms} %{buildroot}/*


%check
make test


%clean
rm -rf %{buildroot}


%files
%defattr(-,root,root,-)
%doc Changes LICENSE README
%{_datadir}/fusioninventory/lib/FusionInventory/Agent/Task/Deploy.pm
%{_datadir}/fusioninventory/lib/FusionInventory/Agent/Task/Deploy
%{_mandir}/man3/*


%changelog
* Sun Apr 15 2012 Remi Collet <remi@fedoraproject.org> - 2.1.0-1
- initial spec for Agent 2.2.0
- Specfile autogenerated by cpanspec 1.78.

