Name:           perl-FusionInventory-Agent
Version:        2.1.14
Release:        1%{?dist}
Summary:        FusionInventory::Agent Perl module
License:        GPL+
Group:          Development/Libraries
URL:            http://search.cpan.org/dist/FusionInventory-Agent/
Source0:        http://www.cpan.org/modules/by-module/FusionInventory/FusionInventory-Agent-%{version}.tar.gz
BuildRoot:      %{_tmppath}/%{name}-%{version}-%{release}-root-%(%{__id_u} -n)
BuildArch:      noarch
BuildRequires:  perl >= 1:5.8.0
BuildRequires:  perl(Compress::Zlib)
BuildRequires:  perl(Crypt::SSLeay)
BuildRequires:  perl(ExtUtils::MakeMaker)
BuildRequires:  perl(File::ShareDir)
BuildRequires:  perl(HTTP::Daemon)
BuildRequires:  perl(HTTP::Server::Simple::Authen)
BuildRequires:  perl(HTTP::Server::Simple::CGI)
BuildRequires:  perl(LWP)
BuildRequires:  perl(Net::CUPS) >= 0.6
BuildRequires:  perl(Net::IP)
BuildRequires:  perl(Proc::Daemon)
BuildRequires:  perl(Proc::PID::File)
BuildRequires:  perl(Test::Exception)
BuildRequires:  perl(Test::More)
BuildRequires:  perl(UNIVERSAL::require)
BuildRequires:  perl(XML::Simple)
BuildRequires:  perl(XML::TreePP)
Requires:       perl(Compress::Zlib)
Requires:       perl(Crypt::SSLeay)
Requires:       perl(File::ShareDir)
Requires:       perl(HTTP::Daemon)
Requires:       perl(LWP)
Requires:       perl(Net::CUPS) >= 0.6
Requires:       perl(Net::IP)
Requires:       perl(Proc::Daemon)
Requires:       perl(Proc::PID::File)
Requires:       perl(UNIVERSAL::require)
Requires:       perl(XML::Simple)
Requires:       perl(:MODULE_COMPAT_%(eval "`%{__perl} -V:version`"; echo $version))

%description
if (!$ENV{TEST_AUTHOR}) {    my $msg = 'Author test. Set $ENV{TEST_AUTHOR}
to a true value to run.';    plan(skip_all => $msg); }

%prep
%setup -q -n FusionInventory-Agent-%{version}

%build
%{__perl} Makefile.PL INSTALLDIRS=vendor
make %{?_smp_mflags}

%install
rm -rf $RPM_BUILD_ROOT

make pure_install PERL_INSTALL_ROOT=$RPM_BUILD_ROOT

find $RPM_BUILD_ROOT -type f -name .packlist -exec rm -f {} \;
find $RPM_BUILD_ROOT -depth -type d -exec rmdir {} 2>/dev/null \;

%{_fixperms} $RPM_BUILD_ROOT/*

%check
make test

%clean
rm -rf $RPM_BUILD_ROOT

%files
%defattr(-,root,root,-)
%doc AUTHORS Changes fusioninventory-agent fusioninventory-agent-config fusioninventory-injector fusioninventory-win32-service LICENSE memconf MYMETA.yml THANKS
%{perl_vendorlib}/*
%{_mandir}/man3/*

%changelog
* Sat Apr 14 2012 http://blog.famillecollet.com 2.1.14-1
- Specfile autogenerated by cpanspec 1.78.
