Name:           perl-Gtk2-WebKit
Version:        0.09
Release:        1%{?dist}
Summary:        Web content engine library for Gtk2
License:        LGPLv2+
Group:          Development/Libraries
URL:            http://search.cpan.org/dist/Gtk2-WebKit/
Source0:        http://www.cpan.org/modules/by-module/Gtk2/Gtk2-WebKit-%{version}.tar.gz

BuildRoot:      %{_tmppath}/%{name}-%{version}-%{release}-root-%(%{__id_u} -n)
BuildRequires:  perl >= 1:5.8.0
BuildRequires:  perl(ExtUtils::MakeMaker)
BuildRequires:  perl(ExtUtils::Depends)
BuildRequires:  perl(ExtUtils::PkgConfig)
BuildRequires:  perl(Gtk2)
BuildRequires:  perl(Test::More) >= 0.89
BuildRequires:  webkitgtk-devel
BuildRequires:  perl-Glib-devel

Requires:       perl(Gtk2)
Requires:       perl(:MODULE_COMPAT_%(eval "`%{__perl} -V:version`"; echo $version))

%{?perl_default_filter}


%description
WebKit is a web content engine, derived from KHTML and KJS from KDE, and
used primarily in Apple's Safari browser. It is made to be embedded in
other applications, such as mail readers, or web browsers.


%prep
%setup -q -n Gtk2-WebKit-%{version}


%build
%{__perl} Makefile.PL INSTALLDIRS=vendor OPTIMIZE="$RPM_OPT_FLAGS"
make %{?_smp_mflags}


%install
rm -rf $RPM_BUILD_ROOT

make pure_install PERL_INSTALL_ROOT=$RPM_BUILD_ROOT

find $RPM_BUILD_ROOT -type f -name .packlist -exec rm -f {} \;
find $RPM_BUILD_ROOT -type f -name '*.bs' -size 0 -exec rm -f {} \;
find $RPM_BUILD_ROOT -depth -type d -exec rmdir {} 2>/dev/null \;

%{_fixperms} $RPM_BUILD_ROOT/*


%check
echo "make test disabled, requires a display"


%clean
rm -rf $RPM_BUILD_ROOT


%files
%defattr(-,root,root,-)
# request for License
# https://rt.cpan.org/Public/Bug/Display.html?id=70048
%doc Changes maps README
%{perl_vendorarch}/auto/Gtk2
%{perl_vendorarch}/Gtk2/*
%{_mandir}/man3/Gtk2*


%changelog
* Thu Aug 04 2011 Remi Collet <remi@fedoraproject.org> 0.09-1
- initial package for review
- Specfile autogenerated by cpanspec 1.78.
