Name:           perl-HTTP-Server-Simple-Authen
Version:        0.04
Release:        1%{?dist}
Summary:        Authentication plugin for HTTP::Server::Simple
# https://rt.cpan.org/Public/Bug/Display.html?id=71033
# You can redistribute it and/or modify it under the same terms as Perl itself.
License:        GPL+ or Artistic
Group:          Development/Libraries
URL:            http://search.cpan.org/dist/HTTP-Server-Simple-Authen/
Source0:        http://www.cpan.org/modules/by-module/HTTP/HTTP-Server-Simple-Authen-%{version}.tar.gz

BuildArch:      noarch
BuildRequires:  perl(Authen::Simple) >= 0.04
BuildRequires:  perl(ExtUtils::MakeMaker)
BuildRequires:  perl(HTTP::Server::Simple) >= 0.16
BuildRequires:  perl(Test::More) >= 0.32

Requires:       perl(Authen::Simple) >= 0.04
Requires:       perl(HTTP::Server::Simple) >= 0.16
Requires:       perl(Test::More) >= 0.32
Requires:       perl(:MODULE_COMPAT_%(eval "`%{__perl} -V:version`"; echo $version))

%{?perl_default_filter}


%description
HTTP::Server::Simple::Authen is an HTTP::Server::Simple plugin to allow
HTTP authentication. Authentication scheme is pluggable and you can use
whatever Authentication protocol that Authen::Simple supports.


%prep
%setup -q -n HTTP-Server-Simple-Authen-%{version}


%build
%{__perl} Makefile.PL INSTALLDIRS=vendor
make %{?_smp_mflags}


%install
rm -rf %{buildroot}

make pure_install PERL_INSTALL_ROOT=%{buildroot}

find %{buildroot} -type f -name .packlist -exec rm -f {} \;
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null \;

%{_fixperms} %{buildroot}/*


%check
make test


%files
%doc Changes
%{perl_vendorlib}/HTTP/Server/Simple/*
%{_mandir}/man3/HTTP*


%changelog
* Wed Sep 14 2011 Remi Collet <remi@fedoraproject.org> 0.04-1
- Specfile autogenerated by cpanspec 1.78.
- minor cleanup
