# spec file for perl-GStreamer1
#
# Copyright (c) 2015 Remi Collet
# License: CC-BY-SA
# http://creativecommons.org/licenses/by-sa/4.0/
#
# Please, preserve the changelog entries
#

Name:           perl-GStreamer1
Version:        0.003
Release:        2%{?dist}
Summary:        Bindings for GStreamer 1.x
# Full text of the License in the headers is enough,
# But https://rt.cpan.org/Ticket/Display.html?id=102878
License:        BSD
URL:            http://search.cpan.org/dist/GStreamer1/
Source0:        http://search.cpan.org/CPAN/authors/id/T/TM/TMURRAY/GStreamer1-%{version}.tar.gz

BuildArch:      noarch
BuildRequires:  perl
BuildRequires:  perl(strict)
BuildRequires:  perl(warnings)
%if 0%{?fedora} > 21
BuildRequires:  perl(ExtUtils::MakeMaker) >= 6.76
%else
BuildRequires:  perl(ExtUtils::MakeMaker) >= 6.30
%endif
BuildRequires:  perl(Devel::CheckLib)
BuildRequires:  perl(Glib::Object::Introspection) >= 0.009
BuildRequires:  perl(Test::Pod)
BuildRequires:  perl(Test::More)
BuildRequires:  gstreamer1-devel
BuildRequires:  gstreamer1-plugins-base

Requires:       perl(:MODULE_COMPAT_%(eval "`%{__perl} -V:version`"; echo $version))
# For Gst-1.0.typelib, GstBase-1.0.typelib and GstController-1.0.typelib
Requires:       gstreamer1
# For GstApp-1.0.typelib
Requires:       gstreamer1-plugins-base

%{?perl_default_filter}


%description
GStreamer1 implements a framework that allows for processing and encoding
of multimedia sources in a manner similar to a shell pipeline.

This package provides the perl language bindings.


%prep
%setup -q -n GStreamer1-%{version}


%build
%if 0%{?fedora} > 21
perl Makefile.PL INSTALLDIRS=vendor NO_PACKLIST=1
%else
perl Makefile.PL INSTALLDIRS=vendor
%endif
make %{?_smp_mflags}


%install
make pure_install PERL_INSTALL_ROOT=%{buildroot}

%if 0%{?fedora} <= 21
find %{buildroot} -type f -name .packlist -exec rm -f {} \;
find %{buildroot} -type f -name '*.bs' -size 0 -exec rm -f {} \;
%endif

%{_fixperms} %{buildroot}/*


%check
make test


%files
%doc CHANGELOG dist.ini examples
%{perl_vendorlib}/GStreamer1*
%{_mandir}/man3/GStreamer1*


%changelog
* Thu Mar 19 2015 Remi Collet <remi@fedoraproject.org> - 0.003-2
- fix Source0 and comments from review #1203610

* Thu Mar 19 2015 Remi Collet <remi@fedoraproject.org> - 0.003-1
- Specfile autogenerated by cpanspec 1.78.
- cleanup (thanks eseyman)