Name:           FusionInventory-Agent-Task-ESX
Version:        1.1.3
Release:        1%{?dist}
Summary:        FusionInventory::Agent::Task::ESX Perl module
License:        GPL+
Group:          Development/Libraries
URL:            http://search.cpan.org/dist/FusionInventory-Agent-Task-ESX/
Source0:        http://www.cpan.org/modules/by-module/FusionInventory/FusionInventory-Agent-Task-ESX-%{version}.tar.gz
BuildRoot:      %{_tmppath}/%{name}-%{version}-%{release}-root-%(%{__id_u} -n)
BuildArch:      noarch
BuildRequires:  perl >= 1:5.8.0
BuildRequires:  perl(ExtUtils::MakeMaker)
BuildRequires:  perl(FusionInventory::Agent) >= 	
BuildRequires:  perl(HTTP::Cookies)
BuildRequires:  perl(JSON)
BuildRequires:  perl(LWP::UserAgent)
BuildRequires:  perl(Test::Exception)
BuildRequires:  perl(Test::More)
BuildRequires:  perl(XML::TreePP)
Requires:       perl(FusionInventory::Agent) >= 	
Requires:       perl(HTTP::Cookies)
Requires:       perl(JSON)
Requires:       perl(LWP::UserAgent)
Requires:       perl(XML::TreePP)
Requires:       perl(:MODULE_COMPAT_%(eval "`%{__perl} -V:version`"; echo $version))

%description
You can import the generated files in:
- GLPI with FusionInventory for GLPI
- ocsinventory
- Uranos

%prep
%setup -q

%build
%{__perl} Makefile.PL INSTALLDIRS=vendor
make %{?_smp_mflags}

%install
rm -rf $RPM_BUILD_ROOT

make pure_install PERL_INSTALL_ROOT=$RPM_BUILD_ROOT

find $RPM_BUILD_ROOT -type f -name .packlist -exec rm -f {} \;
find $RPM_BUILD_ROOT -depth -type d -exec rmdir {} 2>/dev/null \;

%{_fixperms} $RPM_BUILD_ROOT/*

%check
make test

%clean
rm -rf $RPM_BUILD_ROOT

%files
%defattr(-,root,root,-)
%doc AUTHOR Changes fusioninventory-esx LICENSE MYMETA.yml README
%{perl_vendorlib}/*
%{_mandir}/man3/*

%changelog
* Sun Apr 15 2012 http://blog.famillecollet.com 1.1.3-1
- Specfile autogenerated by cpanspec 1.78.
