Name:           FusionInventory-Agent-Task-NetDiscovery
Version:        1.5
Release:        1%{?dist}
Summary:        SNMP support for FusionInventory Agent
License:        GPL+
Group:          Development/Libraries
URL:            http://search.cpan.org/dist/FusionInventory-Agent-Task-NetDiscovery/
Source0:        http://www.cpan.org/modules/by-module/FusionInventory/FusionInventory-Agent-Task-NetDiscovery-%{version}.tar.gz
BuildRoot:      %{_tmppath}/%{name}-%{version}-%{release}-root-%(%{__id_u} -n)
BuildArch:      noarch
BuildRequires:  perl >= 1:5.6.0
BuildRequires:  perl(ExtUtils::MakeMaker)
BuildRequires:  perl(FusionInventory::Agent) >= 2.0
BuildRequires:  perl(Net::IP)
BuildRequires:  perl(Net::NBName)
BuildRequires:  perl(Net::SNMP)
BuildRequires:  perl(Parallel::ForkManager)
BuildRequires:  perl(threads)
BuildRequires:  perl(XML::Simple)
BuildRequires:  perl(XML::TreePP)
Requires:       perl(FusionInventory::Agent) >= 2.0
Requires:       perl(Net::IP)
Requires:       perl(Net::NBName)
Requires:       perl(Net::SNMP)
Requires:       perl(Parallel::ForkManager)
Requires:       perl(threads)
Requires:       perl(XML::Simple)
Requires:       perl(XML::TreePP)
Requires:       perl(:MODULE_COMPAT_%(eval "`%{__perl} -V:version`"; echo $version))

%description
This module scans your networks to get informations from devices with the
SNMP protocol

%prep
%setup -q

%build
%{__perl} Makefile.PL INSTALLDIRS=vendor
make %{?_smp_mflags}

%install
rm -rf $RPM_BUILD_ROOT

make pure_install PERL_INSTALL_ROOT=$RPM_BUILD_ROOT

find $RPM_BUILD_ROOT -type f -name .packlist -exec rm -f {} \;
find $RPM_BUILD_ROOT -depth -type d -exec rmdir {} 2>/dev/null \;

%{_fixperms} $RPM_BUILD_ROOT/*

%check
make test

%clean
rm -rf $RPM_BUILD_ROOT

%files
%defattr(-,root,root,-)
%doc AUTHORS Changes LICENSE README THANKS
%{perl_vendorlib}/*
%{_mandir}/man3/*

%changelog
* Sun Apr 15 2012 http://blog.famillecollet.com 1.5-1
- Specfile autogenerated by cpanspec 1.78.
