Name:           FusionInventory-Agent-Task-NetDiscovery
Version:        2.1
Release:        1%{?dist}
Summary:        Net discovery support for FusionInventory Agent
License:        GPL+
Group:          Development/Libraries
URL:            http://search.cpan.org/dist/FusionInventory-Agent-Task-NetDiscovery/
Source0:        http://www.cpan.org/modules/by-module/FusionInventory/FusionInventory-Agent-Task-NetDiscovery-%{version}.tar.gz
BuildRoot:      %{_tmppath}/%{name}-%{version}-%{release}-root-%(%{__id_u} -n)
BuildArch:      noarch
BuildRequires:  perl >= 1:5.8.0
BuildRequires:  perl(ExtUtils::MakeMaker)
BuildRequires:  perl(Net::IP)
BuildRequires:  perl(Net::NBName)
BuildRequires:  perl(Net::SNMP)
BuildRequires:  perl(threads)
BuildRequires:  perl(XML::TreePP) >= 0.26
Requires:       perl(Net::IP)
Requires:       perl(Net::NBName)
Requires:       perl(Net::SNMP)
Requires:       perl(threads)
Requires:       perl(XML::TreePP) >= 0.26
Requires:       perl(:MODULE_COMPAT_%(eval "`%{__perl} -V:version`"; echo $version))

%description
This tasks scans the network to find connected devices, allowing:

%prep
%setup -q

%build
%{__perl} Makefile.PL INSTALLDIRS=vendor
make %{?_smp_mflags}

%install
rm -rf $RPM_BUILD_ROOT

make pure_install PERL_INSTALL_ROOT=$RPM_BUILD_ROOT

find $RPM_BUILD_ROOT -type f -name .packlist -exec rm -f {} \;
find $RPM_BUILD_ROOT -depth -type d -exec rmdir {} 2>/dev/null \;

%{_fixperms} $RPM_BUILD_ROOT/*

%check
make test

%clean
rm -rf $RPM_BUILD_ROOT

%files
%defattr(-,root,root,-)
%doc Changes Changes.discovery Changes.inventory LICENSE MYMETA.json MYMETA.yml README THANKS
%{perl_vendorlib}/*
%{_mandir}/man3/*

%changelog
* Sun Apr 15 2012 http://blog.famillecollet.com 2.1-1
- Specfile autogenerated by cpanspec 1.78.
