.TH "FIREFOX" "1" "October 2012" "http://www.mozilla.org" "User Commands"
.SH "NAME"
Firefox \- a Web browser for X11 from the Mozilla Foundation.
.SH "SYNOPSIS"
.B firefox
[\fIOPTIONS\fR] [\fIURL\fR]
.SH "OPTIONS"
Summary of command\-line options:
.PP 
\fBX11 options\fR
.TP 
\fB\-\-display\fR=\fIDISPLAY\fR
X display to use.
.TP 
\fB\-\-sync\fR
Make X calls synchronous.
.TP 
\fB\-\-g\-fatal\-warnings\fR
Make all warnings fatal.
.PP 
\fBFirefox options\fR
.TP 
\fB\-h\fR or \fB\-help\fR
Print all command-line options.
.TP 
\fB\-v\fR or \fB\-version\fR
Print Firefox version.
.TP 
\fB\-P\fR <profile>
Start with <profile>.
.TP 
\fB\-migration\fR
Start with migration wizard.
.TP 
\fB\-ProfileManager\fR
Start with ProfileManager.
.TP 
\fB\-no\-remote\fR
Do not accept or send remote commands; implies \fB\-new\-instance\fR.
.TP 
\fB\-new\-instance\fR
Open new instance, not a new window in running instance.
.TP 
\fB\-UILocale\fR <locale>
Start with <locale> resources as UI Locale.
.TP 
\fB\-safe\-mode\fR
Disables extensions and themes for this session.
.TP 
\fB\-jsconsole\fR
Open the Error console.
.TP 
\fB\-browser\fR
Open a browser window.
.TP 
\fB\-new\-window\fR <url>
Open <url> in a new window.
.TP 
\fB\-new\-tab\fR <url>
Open <url> in a new tab.
.TP 
\fB\-preferences\fR
Open Preferences dialog.
.TP 
\fB\-search\fR <term>
Search <term> with your default search engine.
.TP 
\fB\-private\fR
Enable private browsing mode.
.TP 
\fB\-private\-toggle\fR
Toggle private browsing mode.
.TP 
\fB\-setDefaultBrowser\fR
Set this app as the default browser.
.SH "BUGS"
For packaging related bug reports (including this man page): https://bugzilla.redhat.com/

For application bug reports: https://bugzilla.mozilla.org/
