Name:           perl-FusionInventory-Agent-Task-OcsDeploy
Version:        1.0.3
Release:        1%{?dist}
Summary:        OCS Inventory NG Software deployment support for FusionInventory Agent
Summary(fr):    Gestion du déploiement logiciel OCS Inventory NG avec FusionInventory
License:        GPLv2+
Group:          Development/Libraries

URL:            http://forge.fusioninventory.org/projects/fusioninventory-agent-task-ocsdeploy
Source0:        http://forge.fusioninventory.org/attachments/download/48/FusionInventory-Agent-Task-OcsDeploy-1.0.3.tar.gz

BuildRoot:      %{_tmppath}/%{name}-%{version}-%{release}-root-%(%{__id_u} -n)
BuildArch:      noarch

BuildRequires:  perl(Archive::Extract)
BuildRequires:  perl(ExtUtils::MakeMaker)
BuildRequires:  perl(File::Copy::Recursive)
# For tests
BuildRequires:  perl(FusionInventory::Agent) >= 2.0
BuildRequires:  perl(XML::Simple)
BuildRequires:  perl(Test::More)

Requires:       perl(Archive::Extract)
Requires:       perl(File::Copy::Recursive)
Requires:       perl(FusionInventory::Agent) >= 2.0
Requires:       perl(XML::Simple)
Requires:       perl(:MODULE_COMPAT_%(eval "`%{__perl} -V:version`"; echo $version))


%description
With this module, FusionInventory Agent can accept software deployment
request from an OCS Inventory server NG.


%description -l fr
Avec ce module, l'agent FusionInventory peut traiter les ordres de
déploiement de logiciel envoyés par un serveur OCS Inventory NG.


%prep
%setup -q -n FusionInventory-Agent-Task-OcsDeploy-%{version}

# Filtering auto Requires detection
cat <<EOF | tee %{name}-req
#!/bin/sh
%{__perl_requires} $* | \
sed -e '/perl(Win32::/d'
EOF

%global __perl_requires %{_builddir}/FusionInventory-Agent-Task-OcsDeploy-%{version}/%{name}-req
chmod +x %{__perl_requires}


%build
%{__perl} Makefile.PL INSTALLDIRS=vendor
make %{?_smp_mflags}


%install
rm -rf $RPM_BUILD_ROOT

make pure_install DESTDIR=$RPM_BUILD_ROOT

find $RPM_BUILD_ROOT -type f -name .packlist -exec rm -f {} \;
find $RPM_BUILD_ROOT -depth -type d -exec rmdir {} 2>/dev/null \;

%{_fixperms} $RPM_BUILD_ROOT/*


%check
%if 0%{?rhel} == 4
echo "Test disable because Time::Hires not available"
%else
make test
%endif


%clean
rm -rf $RPM_BUILD_ROOT


%files
%defattr(-,root,root,-)
%doc AUTHORS Changes LICENSE README THANKS
%{perl_vendorlib}/FusionInventory/Agent/Task/OcsDeploy.pm
%{_mandir}/man3/Fusion*


%changelog
* Sat May 29 2010 Remi Collet <Fedora@famillecollet.com> - 1.0.3-1
- update to 1.0.3
- add filter for Win32 component
- switch URL to forge

* Fri May 07 2010 Remi Collet <Fedora@famillecollet.com> - 1.0.2-1
- Specfile autogenerated by cpanspec 1.78.
- spec cleanup + translation

