#!/bin/sh
#set -x
TMP=/tmp/liste.$(basename $PWD)

nom=${PWD#/home/rpmbuild/site/rpms/}
if [ "$nom" = "SRPMS" ]
then
  dis=fedora
  ver=26
  old=5
else
  dis=${nom%%/*}
  ver=${nom#$dis/}
  ver=${ver%%/*}
  old=2
fi

if [ ${1:-check} != nocheck ]; then
	echo "+ Controle des signatures"
	rpm -K *.rpm | grep -v 'gpg OK' | cut -d: -f1 | tee $TMP
	if [ -s $TMP ]
	then
		if [ $dis == fedora -a $ver -ge 26 ]
		then rpmsign --define '_gpg_path /home/remi/.gnupg2017' --define "_gpg_name Remi's RPM repository"  --addsign $(cat $TMP)
		else rpmsign --define '_gpg_path /home/remi/.gnupgrpm'  --define "_gpg_name Remi Collet"            --addsign $(cat $TMP)
		fi
	else	echo OK.
	fi
fi

echo "+ Nettoyage des anciens ($old)"

dnf repomanage --old --keep=$old . | tee $TMP
LST=$(cat $TMP)

if [ -z "$LST" ]
then	echo OK.
else	mv $LST /data/rpms/old/
fi

cache=/home/rpmbuild/site/rpms/.createrepocache/$nom
mkdir -p $cache
if [ $dis == fedora -a $ver -ge 11 ]
then	check=sha256
elif [ $dis == enterprise -a $ver -ge 6 ]
then	check=sha256
else	check=sha
fi
echo "+ Génération des meta + sql ($check)"
createrepo --workers 4 		 \
           --cachedir $cache 	 \
           --checksum $check 	 \
           --unique-md-filenames \
           --compress-type=bz2   \
           --database .

if [ -d headers ]
then
	echo "+ Génération des headers"
	yum-arch .
fi

echo "+ Génération repoview"
nom=${PWD#/home/rpmbuild/site/rpms/}
echo repoview --url http://rpms.remirepo.net/$nom \
	--template-dir /home/rpmbuild/site/rpms/repotmpl \
	--title "Les RPM de Remi - ${nom//\// - }" .
LANG=C repoview --url http://rpms.remirepo.net/$nom \
	--template-dir /home/rpmbuild/site/rpms/repotmpl \
	--title "Les RPM de Remi - ${nom//\// - }" .

